### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by HendrikRoth** [tcoupin/docker-seafile-sqlite#2]
System error: exec format error.

(after step 3)  https://github.com/tcoupin/docker-seafile-sqlite/blob/master/Dockerfile#L4

Sorry, i don't get more detailed information in this build?

**Comment by HendrikRoth** [comment]
Ops. Used Dockerfile instead of Dockerfile.pi on my rasp. Closed.

**Comment by tcoupin** [comment]
Docker image is available at https://hub.docker.com/r/tcoupin/rpi-seafile-sqlite/ and https://hub.docker.com/r/tcoupin/seafile-sqlite/ ;)

**Comment by HendrikRoth** [comment]
One question: Do i need you use the command in my docker-compose.yml file?

**Comment by tcoupin** [comment]
Seafile provides only background process so you need keep the tail - f.

The beginning of the command is useful only if you keep the volume mounting
in docker-compose.

**Comment by HendrikRoth** [comment]
ok thanks - and which volume really holds the data? sorry for my dummy questions, i am new at seafile.

**Comment by tcoupin** [comment]
I think seafile-data and seahub-data

2016-10-08 22:34 GMT+02:00 Hendrik Roth <notifications@github.com>:

**Comment by tcoupin** [comment]
I no longer use seafile, I switch to owncloud...

2016-10-08 22:41 GMT+02:00 Thibault Coupin <thibault.coupin@gmail.com>:

**Comment by HendrikRoth** [comment]
oh - why?

**Comment by tcoupin** [comment]
seafile don't store file in a usable format, owncloud provide more apps
(image viewer, document online editing...)

2016-10-08 22:44 GMT+02:00 Hendrik Roth <notifications@github.com>:
